{{- with .Values.postgres }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}
spec:
  instances: {{ .instances }}
  imageName: {{ .imageName }}
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: {{ .database }}
      owner: {{ .owner }}
  postgresql:
    parameters:
      {{- toYaml .parameters | nindent 6 }}
  storage:
    size: {{ .storage.size }}
    {{- with .storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred
{{- end }}
